In [225]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
### Introduction to tensors

In [188]:
scalar = torch.tensor(7)

print(
f"""
Tensor : {scalar}
Dimension : {scalar.ndim}
Shape : {scalar.shape}
"""
)


Tensor : 7
Dimension : 0
Shape : torch.Size([])



In [189]:
vector = torch.tensor([1,2])

print(
f"""
Tensor : {vector}
Dimension : {vector.ndim}
Shape : {vector.shape}
"""
)


Tensor : tensor([1, 2])
Dimension : 1
Shape : torch.Size([2])



In [190]:
matrix = torch.tensor([ [1,2], [3,4] ])

print(
f"""
Tensor : {matrix}
Dimension : {matrix.ndim}
Shape : {matrix.shape}
"""
)


Tensor : tensor([[1, 2],
        [3, 4]])
Dimension : 2
Shape : torch.Size([2, 2])



---
### Random Tensors

In [191]:
random_tensor = torch.rand(2,3)

random_tensor

tensor([[0.9408, 0.1332, 0.9346],
        [0.5936, 0.8694, 0.5677]])

In [192]:
random_image_tensor = torch.rand(224,224,3) #height, width, color channels

random_image_tensor

tensor([[[7.4109e-01, 4.2940e-01, 8.8544e-01],
         [5.7390e-01, 2.6658e-01, 6.2745e-01],
         [2.6963e-01, 4.4136e-01, 2.9692e-01],
         ...,
         [3.9324e-01, 4.5545e-02, 4.2129e-01],
         [8.5366e-01, 5.6972e-01, 2.0877e-01],
         [6.5391e-01, 3.3968e-01, 9.5650e-01]],

        [[6.6023e-02, 3.4206e-01, 1.7213e-02],
         [3.0308e-01, 6.5762e-01, 9.8131e-01],
         [5.8397e-01, 9.9018e-01, 5.9783e-01],
         ...,
         [4.2213e-01, 4.8892e-01, 2.9742e-01],
         [6.8196e-01, 5.3223e-01, 8.5103e-01],
         [4.5559e-01, 1.8443e-01, 8.5328e-01]],

        [[5.6982e-01, 3.5680e-01, 1.7045e-01],
         [6.1719e-01, 2.3124e-02, 6.3169e-01],
         [7.4722e-01, 6.1400e-02, 1.7266e-01],
         ...,
         [4.5285e-01, 8.4301e-01, 2.0853e-01],
         [6.7919e-01, 4.9887e-01, 9.3264e-02],
         [3.0635e-01, 6.2724e-01, 5.9552e-01]],

        ...,

        [[1.7798e-01, 9.0903e-04, 2.9150e-01],
         [8.8188e-01, 3.5989e-01, 1.9892e-01]

In [193]:
zeros = torch.zeros(3,4)

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [194]:
ones = torch.ones(3,4)

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [195]:
rng = torch.arange(0,10)

rng

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
like = torch.zeros_like(rng)

like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

---
### Tensor Datatype

**Three Common Errors**
1. Tensors not right datatype `tensor.dtype`
2. Tensors not right shape `tensor.shape`
3. Tensors not on the right device `tensort.device`

In [197]:
float_32_tensor = torch.tensor(
    [3,4,5],
    dtype=torch.float32, # datatype of tensor
    device="cpu", # device the tensor runs on cpu/cuda
    requires_grad=False # trakcs the gradient of tensor's operations
)

float_32_tensor.dtype

torch.float32

In [198]:
# Type conversion
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

---
### Manipulating Tensors (Operations)

In [199]:
tensor_1 = torch.rand(10)

tensor_1 + 10, tensor_1 - 10, tensor_1 * 10, tensor_1 / 10

(tensor([10.4117, 10.0992, 10.3078, 10.7786, 10.8016, 10.3649, 10.6286, 10.9663,
         10.7687, 10.4566]),
 tensor([-9.5883, -9.9008, -9.6922, -9.2214, -9.1984, -9.6351, -9.3714, -9.0337,
         -9.2313, -9.5434]),
 tensor([4.1173, 0.9923, 3.0780, 7.7864, 8.0156, 3.6490, 6.2857, 9.6626, 7.6870,
         4.5663]),
 tensor([0.0412, 0.0099, 0.0308, 0.0779, 0.0802, 0.0365, 0.0629, 0.0966, 0.0769,
         0.0457]))

---
### Matrix Operations
1. Elementwise
2. Dot Product
3. Transpose

In [200]:
# Elementwise Multiplication
tensor = torch.tensor([1,2,3,4,5])

tensor*tensor

tensor([ 1,  4,  9, 16, 25])

In [201]:
# Matrix Multiplication (Dot Products)
torch.matmul(tensor, tensor)

tensor(55)

In [202]:
# Transpose
tensor.T

tensor([1, 2, 3, 4, 5])

---
### Min, Max, Mean, Sum (Aggregation)

In [203]:
x = torch.arange(0,10)

In [204]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [205]:
# Max
torch.max(x), x.max()

(tensor(9), tensor(9))

In [206]:
# Mean
torch.mean(x.type(torch.float64)), x.type(torch.float64).mean()

(tensor(4.5000, dtype=torch.float64), tensor(4.5000, dtype=torch.float64))

In [207]:
# Sum
torch.sum(x), x.sum()

(tensor(45), tensor(45))

In [208]:
# Min-Max Index
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [209]:
# Using Torch Methods
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

---
### Resphaping, Stacking, Squeezing & Unsqueezing Tesnors
1. Reshaping
    - Reshapes an input tensor to a defined shape
2. View
    - Returns a view of an input tensor, but keeps the original memory of the tensor
3. Stacking
    - Combine multiple tensors of on top of eachother (VStack) or side by side (HStack)
4. Squeeze
    - Removes all `1` dimensions from a tensor
5. Unaqueeze
    - Add a `1` dimension to a target tensor
6. Permute
    - Return a view of the input with dimensions permutated(swapped) in a certain way

In [210]:
x = torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [211]:
# Reshape
x_reshaped = x.reshape(3,4)
x_reshaped

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [212]:
# View
z = x.view(2,6) # changin z will change x as it is a view
z

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [213]:
# Checking if original updates based on view
z[0][0] = 5

z, x

(tensor([[ 5,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [214]:
# Stack
x1 = torch.arange(0,5)
x2 = torch.arange(0,5)
v_stack = torch.stack([x1,x2], dim=0)
h_stack = torch.stack([x1,x2], dim=1)

print(f"VStack \n{v_stack}\nHStack  \n{h_stack}")

VStack 
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])
HStack  
tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])


In [215]:
# Squeeze & Unsqeueeze
x = torch.tensor([[1,2,3,4,5]])
x.shape

torch.Size([1, 5])

In [216]:
x_squeezed = x.squeeze()

x_squeezed, x_squeezed.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [217]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [218]:
# Permute
x = torch.rand(224,224,3) # height, width, color channel
x

tensor([[[0.5745, 0.9200, 0.3230],
         [0.8613, 0.0919, 0.3102],
         [0.9536, 0.6002, 0.0351],
         ...,
         [0.6501, 0.1374, 0.3852],
         [0.7029, 0.0650, 0.1280],
         [0.0728, 0.4482, 0.8423]],

        [[0.3919, 0.1191, 0.7616],
         [0.9423, 0.8760, 0.9324],
         [0.3308, 0.0646, 0.4916],
         ...,
         [0.4601, 0.4145, 0.8877],
         [0.7979, 0.1490, 0.8975],
         [0.3493, 0.3416, 0.2586]],

        [[0.9752, 0.2840, 0.2329],
         [0.7765, 0.1522, 0.3084],
         [0.0165, 0.2109, 0.1842],
         ...,
         [0.7706, 0.6538, 0.3952],
         [0.1024, 0.6485, 0.3496],
         [0.7555, 0.3809, 0.3577]],

        ...,

        [[0.8716, 0.6351, 0.7019],
         [0.3454, 0.4896, 0.8905],
         [0.9717, 0.3601, 0.9916],
         ...,
         [0.7278, 0.2134, 0.2524],
         [0.1369, 0.8770, 0.7452],
         [0.5307, 0.9066, 0.6534]],

        [[0.2118, 0.8450, 0.1104],
         [0.3851, 0.9572, 0.7999],
         [0.

In [219]:
x.permute(2,0,1) # color channel, height, width

tensor([[[0.5745, 0.8613, 0.9536,  ..., 0.6501, 0.7029, 0.0728],
         [0.3919, 0.9423, 0.3308,  ..., 0.4601, 0.7979, 0.3493],
         [0.9752, 0.7765, 0.0165,  ..., 0.7706, 0.1024, 0.7555],
         ...,
         [0.8716, 0.3454, 0.9717,  ..., 0.7278, 0.1369, 0.5307],
         [0.2118, 0.3851, 0.3918,  ..., 0.8415, 0.8405, 0.0070],
         [0.5102, 0.2908, 0.5139,  ..., 0.4984, 0.8660, 0.1140]],

        [[0.9200, 0.0919, 0.6002,  ..., 0.1374, 0.0650, 0.4482],
         [0.1191, 0.8760, 0.0646,  ..., 0.4145, 0.1490, 0.3416],
         [0.2840, 0.1522, 0.2109,  ..., 0.6538, 0.6485, 0.3809],
         ...,
         [0.6351, 0.4896, 0.3601,  ..., 0.2134, 0.8770, 0.9066],
         [0.8450, 0.9572, 0.2505,  ..., 0.9385, 0.6385, 0.9709],
         [0.6497, 0.6484, 0.3529,  ..., 0.0323, 0.2001, 0.6855]],

        [[0.3230, 0.3102, 0.0351,  ..., 0.3852, 0.1280, 0.8423],
         [0.7616, 0.9324, 0.4916,  ..., 0.8877, 0.8975, 0.2586],
         [0.2329, 0.3084, 0.1842,  ..., 0.3952, 0.3496, 0.

---
### Indexing
*Similar to numpy*

In [220]:
x = torch.rand(3,3,3)
x

tensor([[[0.3588, 0.9211, 0.8627],
         [0.8223, 0.5248, 0.5881],
         [0.2746, 0.3791, 0.2975]],

        [[0.6450, 0.0163, 0.9160],
         [0.5888, 0.8403, 0.4761],
         [0.7140, 0.4644, 0.6362]],

        [[0.8892, 0.1317, 0.7164],
         [0.2706, 0.6560, 0.6614],
         [0.3648, 0.1490, 0.8693]]])

In [221]:
x[:,:,0], x[:, 0, :], x[0, :, :]

(tensor([[0.3588, 0.8223, 0.2746],
         [0.6450, 0.5888, 0.7140],
         [0.8892, 0.2706, 0.3648]]),
 tensor([[0.3588, 0.9211, 0.8627],
         [0.6450, 0.0163, 0.9160],
         [0.8892, 0.1317, 0.7164]]),
 tensor([[0.3588, 0.9211, 0.8627],
         [0.8223, 0.5248, 0.5881],
         [0.2746, 0.3791, 0.2975]]))

---
### Pytorch & Numpy

In [222]:
arr = np.arange(1,10)

tens = torch.from_numpy(arr).type(torch.float32)
tens

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [223]:
numpy_tensor = tens.numpy()
numpy_tensor

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

---
### Reproducability (Removing Randomness)

In [224]:
torch.manual_seed(42)
x1 = torch.rand(2,4)

torch.manual_seed(42)
x2 = torch.rand(2,4)

x1 == x2

tensor([[True, True, True, True],
        [True, True, True, True]])

---
### Device Agnostic Tensors

In [226]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [227]:
x = torch.tensor([1,2,3], device=device)
x, x.device

(tensor([1, 2, 3]), device(type='cpu'))

In [230]:
# To convert tensor to numpy convert from cuda to cpu first
x.to(device="cpu").numpy() # can also use x.cpu() directly

array([1, 2, 3])